#!/usr/bin/env bash
set -euo pipefail
# ----------------------------
# Hyperparameters:

epochs=150
# ----------------------------

# EXPERIMENTS

# ----------------------------
# Experimento 1
# Parameters:
exp_name="bathymetry"
mesh_type="bathymetry"
mesh_nodes="14, 6"
g2m_m2g_conect=1
# ----------------------------
# This script creates a hierarchical mesh with non-crossing edges guided by bathymetry and trains a model on it.
./seacast_cli/bin/seacast train -e ${epochs} -n ${exp_name} -m ${mesh_type} -o "${mesh_nodes}" -c ${g2m_m2g_conect}
last_dir_name=$(basename "$(ls -td ${HOME}/Seacast/saved_models/*/ | head -n 1)")
printf "%s\n" "$last_dir_name"
./seacast_cli/bin/seacast predict -c ${last_dir_name} -d cuda

# ----------------------------
# Experimento 2
# Parameters:
exp_name="bathymetry"
mesh_type="bathymetry"
mesh_nodes="14, 6"
g2m_m2g_conect=2
# ----------------------------
# This script creates a hierarchical mesh with non-crossing edges guided by bathymetry and trains a model on it.
./seacast_cli/bin/seacast train -e ${epochs} -n ${exp_name} -m ${mesh_type} -o "${mesh_nodes}" -c ${g2m_m2g_conect}
last_dir_name=$(basename "$(ls -td ${HOME}/Seacast/saved_models/*/ | head -n 1)")
printf "%s\n" "$last_dir_name"
./seacast_cli/bin/seacast predict -c ${last_dir_name} -d cuda

# ----------------------------
# Experimento 3
# Parameters:
exp_name="bathymetry"
mesh_type="bathymetry"
mesh_nodes="14, 6"
g2m_m2g_conect=3
# ----------------------------
# This script creates a hierarchical mesh with non-crossing edges guided by bathymetry and trains a model on it.
./seacast_cli/bin/seacast train -e ${epochs} -n ${exp_name} -m ${mesh_type} -o "${mesh_nodes}" -c ${g2m_m2g_conect}
last_dir_name=$(basename "$(ls -td ${HOME}/Seacast/saved_models/*/ | head -n 1)")
printf "%s\n" "$last_dir_name"
./seacast_cli/bin/seacast predict -c ${last_dir_name} -d cuda

# ----------------------------
# Experimento 4
# Parameters:
exp_name="bathymetry"
mesh_type="bathymetry"
mesh_nodes="14, 6"
g2m_m2g_conect=4
# ----------------------------
# This script creates a hierarchical mesh with non-crossing edges guided by bathymetry and trains a model on it.
./seacast_cli/bin/seacast train -e ${epochs} -n ${exp_name} -m ${mesh_type} -o "${mesh_nodes}" -c ${g2m_m2g_conect}
last_dir_name=$(basename "$(ls -td ${HOME}/Seacast/saved_models/*/ | head -n 1)")
printf "%s\n" "$last_dir_name"
./seacast_cli/bin/seacast predict -c ${last_dir_name} -d cuda

# ----------------------------
# Experimento 5
# Parameters:
exp_name="bathymetry"
mesh_type="bathymetry"
mesh_nodes="14, 6"
g2m_m2g_conect=5
# ----------------------------
# This script creates a hierarchical mesh with non-crossing edges guided by bathymetry and trains a model on it.
./seacast_cli/bin/seacast train -e ${epochs} -n ${exp_name} -m ${mesh_type} -o "${mesh_nodes}" -c ${g2m_m2g_conect}
last_dir_name=$(basename "$(ls -td ${HOME}/Seacast/saved_models/*/ | head -n 1)")
printf "%s\n" "$last_dir_name"
./seacast_cli/bin/seacast predict -c ${last_dir_name} -d cuda

# ----------------------------
# Experimento 6
# Parameters:
exp_name="bathymetry"
mesh_type="bathymetry"
mesh_nodes="14, 6"
g2m_m2g_conect=6
# ----------------------------
# This script creates a hierarchical mesh with non-crossing edges guided by bathymetry and trains a model on it.
./seacast_cli/bin/seacast train -e ${epochs} -n ${exp_name} -m ${mesh_type} -o "${mesh_nodes}" -c ${g2m_m2g_conect}
last_dir_name=$(basename "$(ls -td ${HOME}/Seacast/saved_models/*/ | head -n 1)")
printf "%s\n" "$last_dir_name"
./seacast_cli/bin/seacast predict -c ${last_dir_name} -d cuda
# ----------------------------