#!/usr/bin/env bash
set -euo pipefail

# ----------------------------
# Download Data Script
# Parameters:
# CMEMS-username
user=""
# CMEMS-password
password=""
# Start date for data download
start_date="2000-01-01"
end_date="2020-12-31"
# ----------------------------
./seacast_cli/bin/seacast download -u "${user}" -p "${password}" -s "${start_date}" -e "${end_date}"